### ISSUE TITLE
Récupérer l'IP publique

### ISSUE THREAD

**Issue by haruka-7** [nicolargo/openvpnscripts#1]
Bonjour,

Un petit problème dans le script : la commande "wget -qO- whatismyip.org" (server.conf) ne permet plus de remonter l'adresse IP publique sur le serveur VPN, mais remonte du code HTML.

**Comment by nicolargo** [comment]
C'est corrigé ! (Commit https://github.com/nicolargo/openvpnscripts/commit/ee05a79ccb62a45e3d5dd132ee2973cc80c73bfb)

Merci pour le retour
